#!/bin/bash
#SBATCH -p c32m128x2
#SBATCH -n 32
#SBATCH -J metals

for compound in $(ls ../1structures) ; do
 if [ ! -d $compound ] ; then mkdir $compound ; fi ; echo "### $compound ###"
 for length in `seq 30 10 60` ; do
  if [ ! -d $compound/$length ] ; then mkdir $compound/$length ; fi
  for encut in "600" "700" "800" "900" "1000" ; do
    workdir=$compound/$length/$encut
    if [ ! -d $workdir ] ; then mkdir $workdir ; else rm -r $workdir/* ; fi
    cp ../1structures/$compound $workdir/POSCAR
    sed -e "s/encut/${encut}/g"   tINCAR   > $workdir/INCAR
    sed -e "s/length/${length}/g" tKPOINTS > $workdir/KPOINTS
    cd $workdir
    echo "$compound $length $encut is started"
    /home/users/py/albina/bin/vasp/potcar_gen
    srun vasp541-std.04 > out
    rm POTCAR vasprun.xml
    cd ../../..
  done
 done
 echo "$compound done!!!"
done
